### ISSUE TITLE
Research integration with tty-prompt

### ISSUE THREAD

**Issue by xredo** [MarsBased/pathfinder-rails#23]
https://github.com/piotrmurach/tty-prompt

**Comment by oriolbcn** [comment]
looks good to me, we can make the configuration process more fancy :D

**Comment by dvdgs88** [comment]
+ 1, it seems interesting!

**Comment by xredo** [comment]
If it's easy to integrate: +1

**Comment by xredo** [comment]
It is already done in the refactor_branch `feature/refactor-organization`
