### ISSUE TITLE
Replace bower-rails with webpacker

### ISSUE THREAD

**Issue by xredo** [MarsBased/pathfinder-rails#25]

**Comment by pablorc** [comment]
Note that Rails 5.1.0 does have support for webpack. As the changelog say:

>Add Webpack support in new apps via the --webpack option, which will delegate to the rails/webpacker gem.
>
> To generate a new app that has Webpack dependencies configured and binstubs for webpack and webpack-watcher:
> 
> rails new myapp --webpack
> 
> To generate a new app that has Webpack + React configured and an example intalled:
> 
> rails new myapp --webpack=react
> 
> DHH
> 

Source: https://github.com/rails/rails/blob/v5.1.4/railties/CHANGELOG.md
