### ISSUE TITLE
Include automatic testing configuration

### ISSUE THREAD

**Issue by xredo** [MarsBased/pathfinder-rails#26]
- [x] RSpec
- [x] FactoryGirl
- [x] Faker
- [x] Database Cleaner
- [x] Capybara & Poltergeist

**Comment by artero** [comment]
What test suite will be use RSpec or Minitest?

**Comment by xredo** [comment]
This is a discussion that we need to open. For now we can ask the user if he wants to use Rspec or Minitest, but in the future we will want to support only one system.

The problem is that we have not worked with MiniTest enough to have an answer.

**Comment by xredo** [comment]
We will use RSpec as the standard one.

**Comment by dvdgs88** [comment]
We can update to use selenium (the default in rails 5.1.4) and use system tests, consider possible issues with CI config #68  (https://medium.com/table-xi/a-quick-guide-to-rails-system-tests-in-rspec-b6e9e8a8b5f6)

**Comment by pablorc** [comment]
There's only still left the CircleCI + System tests integration. The rest is done in the branch `enhancement/testing`

**Comment by pablorc** [comment]
We are dropping CircleCI support and system tests in this issue. These features now have its own issues at https://github.com/MarsBased/pathfinder-rails/issues/83 and https://github.com/MarsBased/pathfinder-rails/issues/84
