### ISSUE TITLE
Replace Mailcatcher with Letter Opener Web

### ISSUE THREAD

**Issue by xredo** [MarsBased/pathfinder-rails#30]
We are currently planning to open emails in the development environment using Mailcatcher. However, I find that Letter Opener Web has some advantages over Mailcatcher.

See gem documentation for more info: https://github.com/fgrehm/letter_opener_web

Don't confuse with letter_opener, that we discarded in the past because it opened a new browser tab every time an email was sent.

The advantages that I see to change are:

- You don't need to start the Mailcatcher daemon.
- In the environment development.rb file you clearly show that you are using letter_opener_web. With Mailcatcher you are sending to localhost:25
- In staging environments, it's easier to show the letter opener web UI, as it's mounted in the application routes.

WDYT?

**Comment by oriolbcn** [comment]
WOW neat! Didn't know it, I agree on going for it.

My main concern is that it seems it is not very popular, don't know how well maintained it will be, but in any case it's a development dependency so it's not that bad.

**Comment by artero** [comment]
I try in decidim-vilanova a little and looks good

👍
